home-assistant:
  container_name: home-assistant
  restart: unless-stopped
  image: homeassistant/home-assistant
  net: host
  volumes:
    - ~/home-assistant:/config
    - /etc/localtime:/etc/localtime:ro
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
