home-assistant:
  command:
    - 'python -m homeassistant --config /config'
  container_name: home-assistant
  environment:
    - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - LANG=C.UTF-8
    - GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
    - PYTHON_VERSION=3.7.3
    - PYTHON_PIP_VERSION=19.1
  hostname: LINC
  image: homeassistant/home-assistant
  labels:
    maintainer: 'Paulus Schoutsen <Paulus@PaulusSchoutsen.nl>'
  log_driver: json-file
  net: host
  volumes:
    - /home/rich/home-assistant:/config
    - /etc/localtime:/etc/localtime:ro
  working_dir: /usr/src/app
