title: Yolsum
views:
  - title: Dashboard
    id: dashboard
    panel: true
    cards:
      - type: picture-elements
        image: /local/floorplan2.jpg
        elements:
          - entity: light.dining_room
            style:
              left: 77%
              top: 51%
              "--iron-icon-fill-color": white
              "--iron-icon-width": 32px
              "--iron-icon-height": 32px
            icon: mdi:lightbulb-on
            tap_action:
              action: toggle
            type: state-icon
          - entity: light.study
            style:
              left: 26%
              top: 59%
              "--iron-icon-fill-color": white
              "--iron-icon-width": 32px
              "--iron-icon-height": 32px
            icon: mdi:lightbulb-on
            tap_action:
              action: toggle
            type: state-icon
          - entity: light.living_room
            style:
              left: 39%
              top: 42%
              "--iron-icon-fill-color": white
              "--iron-icon-width": 32px
              "--iron-icon-height": 32px
            icon: mdi:lightbulb-on
            tap_action:
              action: toggle
            type: state-icon
          - type: service-button
            title: Turn lights off
            style:
              top: 1%
              left: 1%
              transform: none
              "--primary-color": white
            service: homeassistant.turn_off
            service_data:
              entity_id: group.all_lights
          - type: state-label
            entity: sensor.current_temp
            prefix: "Current temperature: "
            tap_action:
              action: more-info
            style:
              color: white
              'font-weight': 700
              left: 1% 
              top: 5%
              transform: none
          - type: state-label
            entity: sensor.target_temp
            prefix: "Target temperature: "
            tap_action:
              action: more-info
            style:
              color: white
              'font-weight': 700
              left: 1% 
              top: calc(5% + 2em)
              transform: none
          - type: state-label
            entity: person.rich_middleditch
            prefix: "Rich: "
            style:
              color: white
              'font-weight': 700
              left: 1%
              top: calc(5% + 4em)
              transform: none
          - type: state-label
            entity: person.philippa_middleditch
            prefix: "Philippa: "
            style:
              color: white
              'font-weight': 700
              left: 1%
              top: calc(5% + 6em)
              transform: none
          - type: conditional
            conditions:
              - entity: binary_sensor.front_door_outdoor_human
                state: "on"
            elements:
              - type: state-icon
                entity: camera.front_door
                icon: mdi:walk
                tap_action:
                  action: more-info
                style:
                  left: 44%
                  top: 8%
                  "--iron-icon-fill-color": white
                  "--iron-icon-width": 32px
                  "--iron-icon-height": 32px
          - type: conditional
            conditions:
              - entity: binary_sensor.front_door_outdoor_human
                state: "off"
            elements:
              - type: state-icon
                entity: camera.front_door
                icon: mdi:cctv
                tap_action:
                  action: more-info
                style:
                  left: 44%
                  top: 8%
                  "--iron-icon-fill-color": white
                  "--iron-icon-width": 32px
                  "--iron-icon-height": 32px
